services:
  mailpit:
    image: axllent/mailpit:v1.20
    volumes:
      - ./data:/data
    ports:
      - ${MAILPIT_WEB_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_VERBOSE: 1
